@startuml

title Diagrama de Clases: Persona y Estudiante

class Persona {
    + saludar()
}

class Estudiante {
    - nombre: String
    + Estudiante(nombre: String)
    + saludar()
    + saludar(otroNombre: String)
}

Persona <|-- Estudiante

@enduml
